services:
  ip-pinger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ip-pinger
    restart: unless-stopped
    ports:
      - "3300:3300"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - CONFIG_PATH=/app/config.yml
    volumes:
      - /mnt/ip-pinger-data/config.yml:/app/config.yml
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://localhost:3300/health" ]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
