logLevel: debug
alwaysLogErrors: true
prometheusPort: 9090
apiPort: 3300
intervalSecs: 30
devices:
  - source: "Air Light 1"
    ipAddress: "10.10.10.166"
    deviceType: sensor
  - source: Outdoor
    ipAddress: "10.10.10.142"
    deviceType: sensor
  - source: Pool
    ipAddress: "192.168.1.198"
    deviceType: sensor
  - source: Winter Room
    ipAddress: "192.168.1.236"
    deviceType: sensor
